name: Run Tests and Coverage Reporting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Testing on Ubuntu-Latest with Node 12
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: cd functions && npm install

      - name: Create Firebase Service Account File
        run: cd functions && mkdir key
      
      - name: Read Secret and write into service account file
        run: 'cd functions/key && echo "$FIREBASE_SERVICEACCOUNT_KEY" > mate-app-dev-firebase-adminsdk-liq4s-2c859c2b27.json'
        shell: bash
        env:
          FIREBASE_SERICEACCOUNT_KEY: ${{secrets.FIREBASE_SERVICEACCOUNT_KEY}}

      - name: Run tests with coverage and create lcov.info file
        run: cd functions && npm run-script test-with-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
            token: ${{secrets.CODECOV_TOKEN}}
            file: coverage/lcov.info